# Generated by Django 3.0.4 on 2021-02-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentTeacher', '0004_auto_20200418_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='studentTeacher.Answer'),
        ),
    ]
