# Generated by Django 3.0.4 on 2021-02-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentTeacher', '0006_auto_20210208_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, null=True, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='studentTeacher.Answer'),
        ),
    ]
